### ISSUE TITLE
bencode error

### ISSUE THREAD

**Issue by refriedfood** [qfishpear/fishrss#2]
Script was working fine for quite a long time, up until two weeks ago with nothing changed on my end with python, etc.

`
user:~/fishrss$ /usr/bin/python3 "/full/path/to/fishrss/filter.py" --file "/full/path/to/fishrss/test.torrent" --deluge
2021-12-10 15:52:09,817 - INFO - deluge is connected: True
2021-12-10 15:52:09,817 - INFO - api or filter of dic is NOT set
2021-12-10 15:52:09,818 - INFO - api or filter of red is NOT set
2021-12-10 15:52:09,819 - INFO - api and filter of ops are set
2021-12-10 15:52:09,819 - INFO - api or filter of snake is NOT set
2021-12-10 15:52:09,820 - INFO - Traceback (most recent call last):
  File "/full/path/to/fishrss/common.py", line 153, in error_catcher
    func(*args, **kwargs)
  File "/full/path/to/fishrss/filter.py", line 175, in handle_file
    torrent = bencode.decode(raw)
AttributeError: module 'bencode' has no attribute 'decode'
`

Tried uninstalling and reinstall bencode to no avail. The closest I got was manually installing bencode.py, but that caused an error with IPython. This gives the same module 'bencode' has no attribute 'decode' error when running it out of irssi/autodl.
Python 3.6.13

**Comment by qfishpear** [comment]
The bencode library my script using is called "bencode.py". Try uninstall other bencode libraries because they may cause namespace conflict.
Try "pip3 freeze" and see if there is anything related to bencode in it. If that doesn't help, just use `virtualenv` to create a separate python instance for this script

**Comment by refriedfood** [comment]
That's not it. Serverside updated python and the script is fubar, and since this guy has no interest in keeping it up to date, I switched to varroa.
