### ISSUE TITLE
failing check_config

### ISSUE THREAD

**Issue by bleugray** [qfishpear/fishrss#3]
APIs are configured and working correctly with other scripts.  I have tried full access API as well as torrent only.  Do the options in the config file require " around them like the example?  I have tried both ways and neither work.  I am working with the config.py.en.example file.  thanks.  what other info should I provide to help debug?

Thanks

~/fishrss$ python3 check_config.py

2022-01-08 13:21:57,915 - WARNING - dic is not configured
2022-01-08 13:21:57,915 - WARNING - red fail to login
2022-01-08 13:21:57,915 - INFO - Traceback (most recent call last):
  File "check_config.py", line 26, in <module>
    api = get_api(site)
  File "/home/xxxxx/fishrss/common.py", line 64, in get_api
    api = REDApi(
  File "/home/xxxxx/fishrss/gzapi.py", line 203, in __init__
    super().__init__(
  File "/home/xxxxx/fishrss/gzapi.py", line 69, in __init__
    assert os.path.exists(cache_dir), "{}的api_cache_dir文件夹不存在：{}".format(apiname, cache_dir)
AssertionError: red的api_cache_dir文件夹不存在：~/.cache/fishrss/red

2022-01-08 13:21:57,915 - WARNING - ops fail to login
2022-01-08 13:21:57,915 - INFO - Traceback (most recent call last):
  File "check_config.py", line 26, in <module>
    api = get_api(site)
  File "/home/xxxxx/fishrss/common.py", line 87, in get_api
    api = OPSApi(
  File "/home/xxxxx/fishrss/gzapi.py", line 256, in __init__
    super().__init__(
  File "/home/xxxxx/fishrss/gzapi.py", line 69, in __init__
    assert os.path.exists(cache_dir), "{}的api_cache_dir文件夹不存在：{}".format(apiname, cache_dir)
AssertionError: ops的api_cache_dir文件夹不存在：~/.cache/fishrss/ops

2022-01-08 13:21:57,915 - WARNING - snake is not configured
2022-01-08 13:21:57,916 - INFO - can't connect to deluge

**Comment by qfishpear** [comment]
As said in the readme: "Make sure all files and directories in config have been already created by yourself.“
create the following two folders for yourself:
~/.cache/fishrss/red
and
~/.cache/fishrss/ops
or edit `CONFIG["red"]["api_cache_dir"]` and `CONFIG["ops"]["api_cache_dir"]` to somewhere you want
